const {
  default: SignInForm,
} = require("@/components/SignIn/SignInForm/SignInForm");
const {
  default: SignUpOrLoginContainer,
} = require("@/components/SignUpOrLoginContainer/SignUpOrLoginConatainer");
const {
  default: BackComponent,
} = require("@/components/Signup/BackComponent/BackComponent");
const { default: Head } = require("next/head");

import { useRouter } from "next/router";
import styles from "./index.module.css";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { loginWithUserId } from "@/store/LoginState/LoginStateActions";

const RecruiterSignIn = () => {
  const router = useRouter();

  const loginScreenData = {
    description:
      "You’re one step away to unlock all the possible features of Udhyogi ",
    image: "LoginPageScreen.svg",
  };

  const [signUpData, setSignUpData] = useState(null);

  const dispatch = useDispatch();

  const SignUpDataHandler = (data) => {
    setSignUpData(data);
    console.log(data);
    dispatch(loginWithUserId(1, "recruiter"));
    router.push("/recruiter/dashboard");
  };

  return (
    <SignUpOrLoginContainer
      screenData={loginScreenData}
      smallFrame={false}
      classForMainContent={styles.screenContainer}
    >
      <Head>
        <title>IT Recruiter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.formFrame}>
        <div className={styles.head}>
          <BackComponent
            backFunction={() => {
              router.back();
            }}
          />
          <h1 className={styles.heading}>Sign-in</h1>
        </div>
        <SignInForm
          onSubmitCredentials={SignUpDataHandler}
          role={"recruiter"}
        />
      </div>
    </SignUpOrLoginContainer>
  );
};
export default RecruiterSignIn;
