import EducationalDetails from "@/components/Signup/OnBoarding/EducationalDetails/EducationalDetails";
import Head from "next/head";
import { useState } from "react";

const EducationDetails = () => {
  const [educationalDetailsData, setEducationalDetailsData] = useState();

  const HandleUserEducationalDetailsData = (educationalDetailsData) => {
    setEducationalDetailsData(educationalDetailsData);
    console.log(educationalDetailsData);
  };

  return (
    <>
      <Head>
        <title>Education Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EducationalDetails
        onSubmittingEducationalDetails={HandleUserEducationalDetailsData}
      />
    </>
  );
};

export default EducationDetails;
