import WorkExperienceForm from "@/components/Signup/OnBoarding/WorkExperienceForm/WorkExperienceForm";
import Head from "next/head";
import { useState } from "react";

const WorkExperience = () => {
  const [experienceData, setExperienceData] = useState(null);

  const HandleUserExperienceData = (experience) => {
    setExperienceData(experience);
    console.log(experienceData);
  };

  return (
    <>
      <WorkExperienceForm onSubmitExperience={HandleUserExperienceData} />;
      <Head>
        <title>Work Experience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default WorkExperience;
