import SignUpOrLoginContainer from "@/components/SignUpOrLoginContainer/SignUpOrLoginConatainer";
import SignWelcomeScreen from "@/components/Signup/SignWelcomeScreen/SignWelcomeScreen";
import Head from "next/head";

const WelcomeToSignInPage = () => {
  const loginScreenData = {
    description:
      "You’re one step away to unlock all the possible features of Udhyogi ",
    image: "welcomeScreen.svg",
  };

  const welcomeLinks = {
    title: "Sign In",
    buttonLinks: [
      {
        link: "/sign-in/job-provider/admin",
        text: "Admin",
      },
      {
        link: "/sign-in/job-provider/recruiter",
        text: "IT Recruiter",
      },
    ],
    switchLinks: {
      link: "/sign-up",
      text: "Sign up",
    },
  };

  return (
    <div style={{ display: "flex" }}>
      <Head>
        <title>Sign up Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpOrLoginContainer screenData={loginScreenData} smallFrame={false}>
        <SignWelcomeScreen welcomeLinks={welcomeLinks} />
      </SignUpOrLoginContainer>
    </div>
  );
};

export default WelcomeToSignInPage;
