import PreferenceComponent from "@/components/Signup/Preferences/Preferences";
import Head from "next/head";

const Preference = () => {
  return (
    <>
      <Head>
        <title>Job Preference</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PreferenceComponent />;
    </>
  );
};

export default Preference;
