import SignUpOrLoginContainer from "@/components/SignUpOrLoginContainer/SignUpOrLoginConatainer";
import SignWelcomeScreen from "@/components/Signup/SignWelcomeScreen/SignWelcomeScreen";
import Head from "next/head";

const WelcomeToSignUpPage = () => {
  const loginScreenData = {
    description:
      "You’re one step away to unlock all the possible features of Udhyogi ",
    image: "welcomeScreen.svg",
  };

  return (
    <div style={{ display: "flex" }}>
      <Head>
        <title>Sign up Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpOrLoginContainer screenData={loginScreenData} smallFrame={false}>
        <SignWelcomeScreen />
      </SignUpOrLoginContainer>
    </div>
  );
};

export default WelcomeToSignUpPage;
