import { useState } from "react";
import styles from "./index.module.css";
import Experience from "@/components/Signup/OnBoarding/Experience/Experience";
import WorkExperienceForm from "@/components/Signup/OnBoarding/WorkExperienceForm/WorkExperienceForm";
import EducationalDetails from "@/components/Signup/OnBoarding/EducationalDetails/EducationalDetails";
import Head from "next/head";

const OnBoardingPage = () => {
  return (
    <div styles={{ display: "flex" }}>
      <Experience />
      <Head>
        <title>Experience or Fresher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};
export default OnBoardingPage;
