import RootLayout from "@/components/RootLayout/RootLayout";
import MainScreen from "@/components/HomeComponents/MainScreen/MainScreen";
import UsersOptions from "@/components/HomeComponents/UsersOptions/UsersOptions";
import LatestJobs from "@/components/HomeComponents/LatestJobs/LatestJobs";
import CompaniesHiring from "@/components/HomeComponents/CompaniesHiring/CompaniesHiring";
import FraudAlert from "@/components/HomeComponents/FraudAlert/FraudAlert";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [searchData, setSearchData] = useState();

  // useEffect(() => {
  //   if (searchData) {
  //     console.log(searchData);
  //   }
  // }, [searchData]);
  return (
    <RootLayout classForMain={"bg-zinc-100"}>
      <Head>
        <title>Udyogi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainScreen onSearch={setSearchData} />

      <LatestJobs searchData={searchData} />
      <CompaniesHiring />
      <UsersOptions />
      <FraudAlert />
    </RootLayout>
  );
}
