import SignUpOrLoginContainer from "@/components/SignUpOrLoginContainer/SignUpOrLoginConatainer";
import UserSignupFrom from "@/components/Signup/UserSignupFrom/UserSignupFrom";
import styles from "./index.module.css";
import { useRouter } from "next/router";
import CustomImage from "@/components/UI/Image/Image";
import EmailVerified from "@/components/Signup/EmailVerified/EmailVerified";
import EmailVerification from "@/components/Signup/EmailVerification/EmailVerification";
import { useEffect, useState } from "react";
import BackComponent from "@/components/Signup/BackComponent/BackComponent";
import Head from "next/head";
import ForgotPasswordComponent from "@/components/ForgotPasswordComponent/ForgotPasswordComponent";
import ResetPassword from "@/components/ForgotPasswordComponent/ResetPassword";
import PasswordUpdated from "@/components/ForgotPasswordComponent/PasswordUpdated";
import { useParams } from "next/navigation";
const loginScreenData = {
  description:
    "You’re one step away to unlock all the possible features of Udhyogi ",
  image: "signUpScreen.svg",
};

const ForgotPasswordPage = () => {
  const params = useParams();

  useEffect(() => {
    console.log("params", params);
  });

  const [email, setEmail] = useState(null);

  const [otpVerified, setOtpVerified] = useState(false);

  const [newPassword, setNewPassword] = useState(null);

  const getEmail = (email) => {
    console.log(email);
    if (email !== null && email !== undefined) {
      setEmail(email);
    }
  };
  const GetOTP = (otp) => {
    console.log("OTP:", otp);

    if (otp !== undefined && otp !== null && otp !== "") {
      setOtpVerified(true);
    }
  };
  const GetNewPassword = (password) => {
    console.log(password);
    if (password !== undefined && password !== null) {
      setNewPassword(password);
    }
  };

  const MainComponent = (
    <div className="flex justify-center">
      <Head>
        <title>Job Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className={styles.formFrame}>Form</div> */}
      <ForgotPasswordComponent onSubmittingEmail={getEmail} />
    </div>
  );

  const EmailVerificationComponent = (
    <>
      {otpVerified ? (
        <>
          <Head>
            <title>Email Verified</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          {newPassword ? (
            <PasswordUpdated
              action={() => {
                router.push("/sign-in");
              }}
            />
          ) : (
            <ResetPassword onSubmittingPassword={GetNewPassword} />
          )}
        </>
      ) : (
        <>
          <Head>
            <title>Otp Verification</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <EmailVerification onOTPVerify={GetOTP} />
        </>
      )}
    </>
  );

  let ForgetPasswordStructure = <></>;

  if (email === null || !email) {
    ForgetPasswordStructure = MainComponent;
  } else {
    ForgetPasswordStructure = EmailVerificationComponent;
  }

  const router = useRouter();
  return <div styles={{ display: "flex" }}>{ForgetPasswordStructure}</div>;
};
export default ForgotPasswordPage;
